apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: devfile-sample-qtsn
spec:
  replicas: 1
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/pmacik-testing/tkwch-fix-0075-0011-tenant/tkwch-fix-0075-0011-app/devfile-sample-qtsn@sha256:7dbbb8ee12795d2542d8610fa99cff55476310347a09796f6d0e17956ff004ae
        name: my-nodejs
        resources: {}
status: {}
